#!/usr/bin/env bash
set -euo pipefail

# MIDiff inference parameters for the generated MIDiff result chain.
# Note: data/our.csv is real/reference data, not generated by this ckpt.
# The MIDiff generated CSV is produced downstream from midiff
# into exp/results/MIDiff.csv by exp/infer_npz_to_eval_csv.sh.
# sample/inverse-conversion artifacts.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=${ROOT_DIR:-"$(cd "${SCRIPT_DIR}/.." && pwd)"}
PYTHON=${PYTHON:-python}
GPU_IDS=${GPU_IDS:-0}
MPI_N=${MPI_N:-1}

MODEL_PATH=${MODEL_PATH:-${ROOT_DIR}/ckpt/midiff/ema_0.9999_048000.pt}
SAVE_DIR=${SAVE_DIR:-${ROOT_DIR}/ckpt/midiff}

NUM_SAMPLES=${NUM_SAMPLES:-3000}
BATCH_SIZE=${BATCH_SIZE:-64}
IMAGE_SIZE=${IMAGE_SIZE:-256}
IMAGE_SIZE_SECOND=${IMAGE_SIZE_SECOND:-160}
NUM_RES_BLOCKS=${NUM_RES_BLOCKS:-3}
DIFFUSION_STEPS=${DIFFUSION_STEPS:-1000}
NOISE_SCHEDULE=${NOISE_SCHEDULE:-cosine}

cd "${ROOT_DIR}"

CMD=(
  "${PYTHON}" sample_midiff.py
  --model_path "${MODEL_PATH}"
  --save_dir "${SAVE_DIR}"
  --num_samples "${NUM_SAMPLES}"
  --batch_size "${BATCH_SIZE}"
  --image_size "${IMAGE_SIZE}"
  --image_size_second "${IMAGE_SIZE_SECOND}"
  --num_res_blocks "${NUM_RES_BLOCKS}"
  --diffusion_steps "${DIFFUSION_STEPS}"
  --noise_schedule "${NOISE_SCHEDULE}"
  --learn_sigma True
  --class_cond False
  --rescale_learned_sigmas False
  --rescale_timesteps False
  --attention_type triple
)

export CUDA_VISIBLE_DEVICES="${GPU_IDS}"
if [[ "${MPI_N}" -gt 1 ]]; then
  exec mpiexec -n "${MPI_N}" "${CMD[@]}"
else
  exec "${CMD[@]}"
fi
